# Generated by Django 3.2 on 2021-05-03 01:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('idMovie', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('ano', models.ImageField(upload_to='')),
                ('diretor', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('avaliacao', models.ImageField(upload_to='')),
                ('createAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
