# Generated by Django 3.2 on 2021-05-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='title',
            new_name='Titulo',
        ),
        migrations.AlterField(
            model_name='movies',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='avaliacao',
            field=models.IntegerField(),
        ),
    ]
