# Generated by Django 3.2 on 2021-05-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210503_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='avaliacao',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
